#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba32f) uniform imageCube outCubemap;
layout(set = 0, binding = 1) uniform sampler2D equirect;

vec3 GetDirection(uint face, vec2 uv)
{
    switch (face)
    {
    case 0u: return normalize(vec3( 1.0, -uv.y, -uv.x));   // +X
    case 1u: return normalize(vec3(-1.0, -uv.y,  uv.x));   // -X
    case 2u: return normalize(vec3( uv.x,  1.0,  uv.y));   // +Y
    case 3u: return normalize(vec3( uv.x, -1.0, -uv.y));   // -Y
    case 4u: return normalize(vec3( uv.x, -uv.y,  1.0));   // +Z
    case 5u: return normalize(vec3(-uv.x, -uv.y, -1.0));   // -Z
    }
    return vec3(0.0);
}

vec2 ToEquirectUV(vec3 dir)
{
    vec2 uv = vec2(atan(dir.z, dir.x), asin(dir.y));
    uv *= vec2(0.1591, 0.3183);     // 1/(2π), 1/π
    uv += 0.5;
    uv.y = 1.0 - uv.y;              // Equirect top(v = 0) -> Cubemap top(+y)
    return uv;
}

void main()
{
    ivec2 size = imageSize(outCubemap);
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (coord.x >= size.x || coord.y >= size.y)
    {
        return;
    }

    uint face = gl_WorkGroupID.z;

    // UV center, [-1, 1]
    vec2 uv = (vec2(coord) + 0.5) / vec2(size) * 2.0 - 1.0;

    vec3 color = textureLod(equirect, ToEquirectUV(GetDirection(face, uv)), 0.0).rgb;

    imageStore(outCubemap, ivec3(coord, int(face)), vec4(color, 1.0));
}