#version 450

#include "include/cubemap_utils.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba32f) uniform imageCube outCubemap;
layout(set = 0, binding = 1) uniform sampler2D equirect;

// World dir -> Equirect uv
vec2 ToEquirectUV(vec3 dir)
{
    // World dir -> Longitude [-PI, PI] and Latitude [-PI/2, PI/2]
    vec2 uv = vec2(atan(dir.z, dir.x), asin(dir.y));

    // Scale to [-0.5, 0.5], then [0, 1]
    uv *= vec2(0.1591, 0.3183);
    uv += 0.5;
    
    // Flip y: Equirect top(v = 0) mapped to cubemap top(+y)
    uv.y = 1.0 - uv.y;
    
    return uv;
}

void main()
{
    ivec2 size = imageSize(outCubemap).xy;
    ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);

    // Some threads are out of range
    if (pixelCoord.x >= size.x || pixelCoord.y >= size.y)
    {
        return;
    }

    uint face = gl_WorkGroupID.z;
    vec2 faceCoord = (vec2(pixelCoord) + 0.5) / vec2(size) * 2.0 - 1.0;    // Pixel coord center -> [-1, 1]
    
    // Face coord -> World dir -> Equirect uv
    vec2 equirectUV = ToEquirectUV(GetDirection(face, faceCoord));
    
    vec3 color = textureLod(equirect, equirectUV, 0).rgb;

    // Write to cubemap
    imageStore(outCubemap, ivec3(pixelCoord, int(face)), vec4(color, 1.0));
}
